#!/usr/bin/env bash

set -e

darksky-weather() {
  curl -s "https://api.darksky.net/forecast/${DARKSKY_API_KEY}/${1}?units=uk2&exclude=minutely,hourly,daily,alerts,flags"
}

current-weather() {
  darksky-weather "$1" | jq --raw-output '.currently.summary'
}

LOCATION=$(LocateMe -f '{LAT},{LON}')

echo "Date: $(date)"
echo "Location: $LOCATION"
echo "Weather:" $(current-weather "$LOCATION")
