#!/usr/bin/env ruby
require 'uri'

run_as = File.basename($PROGRAM_NAME)

abort "Usage: #{run_as} <string>" if ['-h', '--help', 'help'].include?(ARGV.first)

input = if ARGV.first
  [ARGV.first]
elsif STDIN.tty?
  []
else
  ARGF.readlines
end

encode_or_decode_method = run_as == 'urlencode' ? :encode_www_form_component : :decode_www_form_component

input.map(&:strip).each { |line| puts URI.__send__(encode_or_decode_method, line) }
