#!/bin/sh
set -e

cat <<TEXT
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>${TITLE}</title>
    <style>
      body {
        max-width: 600px;
        margin: 0 auto;
        padding: 10px;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        background-color: #fff;
        color: #333;
      }
    </style>
  </head>
  <body>
    `cat`
  </body>
</html>
TEXT
